version: '3.8'

services:
  postgres:
    image: postgres:15-bookworm
    container_name: postgres-container-cascaron
    environment:
      POSTGRES_DB: cascaron002
      POSTGRES_USER: traxporta
      POSTGRES_PASSWORD: traxporta
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - tms-local

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-container-cascaron
    restart: on-failure
    ports:
      - "8082:5000"
    volumes:
      - ./:/usr/src/src
    depends_on:
      - postgres
    networks:
      - tms-local
    command:
      - poetry
      - run
      - gunicorn
      - --reload
      - -b
      - 0.0.0.0:5000
      - wsgi:src
    environment:
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}

volumes:
  postgres_data:

networks:
  tms-local:
    name: "tmslocal"
    driver: "bridge"